config/routes.rb
Rails.application.routes.draw do
  resources :users, :events
    get 'sign_in' => 'sessions#new', as: :sign_in
  	post 'sign_in' => 'sessions#create'
 	delete 'sign_in' => 'sessions#delete', as: :end_session
 	get 'sign_out' => 'sessions#delete', as: :sign_out

 root 'welcome#calendar'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ActiveRecord::Base

  # scope :between, lambda {|start_time, end_time| {:conditions => ["? < starts_at and starts_at < ?", Event.format_date(start_time), Event.format_date(end_time)] }}
  def self.between(start_time, end_time)
    where('start_at > :lo and start_at < :up',
      :lo => Event.format_date(start_time),
      :up => Event.format_date(end_time)
    )
  end

  def self.format_date(date_time)
   Time.at(date_time.to_i).to_formatted_s(:db)
  end

  def as_json(options = {})
    {
      :id => self.id,
      :title => self.title,
      :start => start_at.rfc822,
      :end => end_at.rfc822,
      :allDay => allDay,
      :username => self.username,
      :url => Rails.application.routes.url_helpers.events_path(id),
      :color => "green"
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action do
      @current_user = User.find_by id: session[:user_id]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      render json: {msg: 'your event was saved.'}
    else
      render json: {msg: 'error: something go wrong.' }, status: 500
    end
  end

  def index
    @events = Event.between(params['start'], params['end']) if (params['start'] && params['end']) 

    respond_to do |format| 
      format.html
      format.json { render :json => @events } 
    end
  end

  def event_params
    params.permit(:title).merge start_at: params[:start].to_time, end_at: params[:end].to_time, username: params[:username]
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by username: params[:username]

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Signed in!"
    else
      flash.now[:alert] = "Something is wrong with your username and/or password"
      render :new
    end
  end

  def delete
    session.delete :user_id
    redirect_to root_path, notice: "Signed Out!"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def index
    before_action do
      if @current_user.nil?
        redirect_to sign_in_path, alert: "Please Sign In"
      end
    end
    @users = User.all
  end


  def show
    before_action do
      if @current_user.nil?
        redirect_to sign_in_path, alert: "Please Sign In"
      end
    end
    @user = User.find_by id: params[:id]
  end

  def edit
    before_action do
      if @current_user.nil?
        redirect_to sign_in_path, alert: "Please Sign In"
      end
    end
    @user = User.find_by id: params[:id]
  end


  def create
   @user = User.create(user_params)
     if @user.save
       # we should also sign them in
       session[:user_id] = @user.id
       redirect_to root_path, notice: "Welcome!"
     else
       render :new
     end
   end

def update
  before_action do
    if @current_user.nil?
      redirect_to sign_in_path, alert: "Please Sign In"
    end
  end
  @user = User.find_by id: params[:id]
    if @user.update(user_params)
      redirect_to dashboard_path, notice: "Profile Updated!"
    else
      render :edit
    end
end

  def profile
    @user = User.find_by id: params[:id]
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :password_digest)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def calendar
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"> Hill Swift Architect, PLLC </a>
            <ul class="nav navbar-nav navbar-right">
		        <%if @current_user%>
			        <li><%= link_to 'Hello ' + @current_user.username, root_path %></li>
			        <li><%= link_to 'Add Entry', new_event_path%></li>
			        <li><%= link_to "Sign Out", sign_out_path%></li>
		        <%else%>
			        <li><%=link_to 'Sign In', sign_in_path%></li>
			        <li><%=link_to 'Create Account', new_user_path%></li>
		        <%end%>
		    </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notices.html.erb
<% if notice %>
<div class="container">
    <div class="alert alert-info" role="alert">
        <%= notice %>
    </div>
</div>
<% end %>

<% if alert %>
<div class="container">
    <div class="alert alert-danger" role="alert">
        <%= alert %>
    </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Atelier</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
  	<%= render 'layouts/notices' %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
	<% @user.errors.full_messages.each do |error| %>
	<p class="alert alert-danger">
	    <strong><%= error %></strong>
	</p>
	<% end %>
<% end %>

<%=simple_form_for @user do |f|%>
<%= f.input :username%>
<div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, size: "60x12", class: "form-control" %>
</div>
<div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, size: "60x12", class: "form-control" %>
</div>

<div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
</div>
<% end %>

app/views/users/destroy.html.erb
<div class="outer-wrapper">
  <div class="container">
    <div class="well">
        <h1>Destroy Account </h1>
        <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="outer-wrapper">
  <div class="container">
    <div class="well">
        <h1>Edit Account Details</h1>
        <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="outer-wrapper">
  <div class="container">
    <div class="well">
        <h1>Users</h1>
        <% for @users.each do |user| %>
        	<%= user.username %>
        <% end%>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="outer-wrapper">
  <div class="container">
    <div class="well">
        <h1>Create A New Account</h1>
        <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<div class="outer-wrapper">
  <div class="container">
    <div class="well">
        <h1>Edit Account Details</h1>
        <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/welcome/calendar.html.erb
<div class='calendar'></div>